
import turtle

PETIOLE_COLOR = 'dark green'
PETIOLE_SHADOW = ''

s = turtle.getscreen()
t = turtle.Turtle()

turtle.title("Shamrock")
turtle.bgcolor("cyan")

   # drawing the clover

def petiole():
    t.pensize(3)
    t.pencolor("black")
    t.speed(5)

    t.up()
    t.right(290)
    t.forward(33)
    t.left(-200)
    t.down()
    t.begin_fill()
    t.fillcolor("dark green")
    t.forward(20)
    t.circle(200, 70)
    t.right(110)
    t.forward(40)
    t.right(82)
    t.circle(-235, 70)
    t.end_fill()

    t.up()
    t.left(170)
    t.forward(30)
def leaf1():
    t.down()
    t.begin_fill()
    t.right(-10)
    t.circle(-225, 70)
    t.left(-35)
    t.circle(-80, 83)
    t.circle(-35, 60)
    t.left(5)
    t.forward(210)
    t.end_fill()

    t.right(-115)
    t.begin_fill()
    t.circle(225, 70)
    t.right(-35)
    t.circle(97, 89)
    t.right(-90)
    t.circle(-40, 40)
    t.forward(210)
    t.end_fill()
def leaf2():
    t.up()
    t.right(-60)
    t.forward(30)
    t.right(-80)
    t.forward(10)
    t.down()
    t.begin_fill()
    t.fillcolor("dark green")
    t.circle(-225, 70)
    t.left(-35)
    t.circle(-80, 83)
    t.circle(-35, 60)
    t.left(5)
    t.forward(210)
    t.end_fill()

    t.right(-115)
    t.begin_fill()
    t.circle(225, 70)
    t.right(-35)
    t.circle(97, 89)
    t.right(-90)
    t.circle(-40, 40)
    t.forward(200)
    t.end_fill()
def leaf3():
    t.up()
    t.left(50)
    t.forward(-2)
    t.left(10)
    t.forward(30)
    t.left(70)
    t.down()
    t.begin_fill()
    t.fillcolor("dark green")
    t.circle(-225, 70)
    t.left(-35)
    t.circle(-80, 83)
    t.circle(-35, 60)
    t.left(5)
    t.forward(210)
    t.end_fill()

    t.right(-115)
    t.begin_fill()
    t.circle(225, 70)
    t.right(-35)
    t.circle(97, 89)
    t.right(-90)
    t.circle(-40, 40)
    t.forward(210)
    t.end_fill()

turtle.hideturtle()
petiole()
leaf1()
leaf2()
leaf3()
t.screen.exitonclick()
